const LOGIN_ACTION = "LOGIN_ACTION";
const LOGOUT_ACTION = "LOGOUT_ACTION";

//Animation Reducer
const FINISHED_QUESTIONS = "GFINISHED_QUESTIONS";

const INCREMENT_PAGE_COUNTER = "INCREMENT_PAGE_COUNTER";
