const LOGIN_ACTION = "LOGIN_ACTION";
const LOGOUT_ACTION = "LOGOUT_ACTION";

const FINISHED_QUESTIONS = "FINISHED_QUESTIONS";
const INCREMENT_PAGE_COUNTER = "INCREMENT_PAGE_COUNTER";

const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
const REMOVE_TO_FAVORITE = "REMOVE_TO_FAVORITE";
